
  
name: "Linters"

on:
  push:
    paths:
      - 'src/**.py'

  pull_request:
    paths:
      - 'src/**.py'

jobs:
  CodeFormat:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Black
      run: |
        pip install 'black==21.9b0'
    - name: Check format
      run: |
        black --check src/
